let shopitemdata = [{
        id:"casualshirt",
        name:"Casual Shirt",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price: 45,
        img:"./images/img-1.jpg"},{ 
        id:"officeshirt",
        name:"Office Shirt",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price: 80,
        img:"./images/img-2.jpg"},{ 
        id:"tshirt",
        name:"T-Shirt",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price: 55,
        img:"./images/img-3.jpg"},{ 
        id:"msuit",
        name:"Suit",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price: 180,
        img:"./images/img-4.jpg"},{
        id: "mtie",
        name: "Mens Tie",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.png",
      }, {
        id: "cshoes",
        name: "Casual shoes",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.png",
      },{
        id: "bsuit",
        name: "black suit",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.png",
      },
      {
        id: "pshirt",
        name: "polo shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-8.png",
      },
      {
        id: "dshirt",
        name: "denim shirt",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-9.png",
      },
      {
        id: "dpants",
        name: "denim pants",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-10.png",
      },
      {
        id: "cap",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-11.png",
      },
      {
        id: "leatherboots",
        name: "leather boots",
        price: 150,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-12.png",
      },    
    
    ]